# Generated by Django 4.1 on 2022-08-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unit_price_product_slug'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO store_collection (title)
        VALUES('collection1')
        """,
        """ 
        DELETE FROM store_collection WHERE title='collection1'
        """)
    ]
